# Generated by Django 3.2 on 2021-06-06 04:33

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210606_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ImageField(upload_to=posts.models.user_directory_path),
        ),
    ]
