# Generated by Django 3.2 on 2021-06-07 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('profileid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profilepic', models.ImageField(upload_to=profiles.models.user_directory_path)),
                ('bio', models.TextField()),
                ('livesin', models.TextField()),
                ('worksat', models.TextField()),
                ('userprofile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
